### ISSUE TITLE
Self Hosting Section Missing

### ISSUE THREAD

**Issue by The-Real-Thisas** [andrewcourtice/ocula#142]
# Missing self-hosting documentation 

I have attempted to set up ocula using a .env file but faced issues with getting it to work. An updated README file to help spin up a local development environment would really help out. And also could you state instructions on how to get ocula to run locally as I'm finding it a bit difficult. Thanks in advance.

**Comment by andrewcourtice** [comment]
Hi @The-Real-Thisas - Apologies for that. I will add it back into the documentation shortly 👍

**Comment by inezabonte** [comment]
@andrewcourtice how can I reach you?

**Comment by igolyudov** [comment]
how can i run localy without run vercel?

**Comment by julian-fairfax** [comment]
This would still be useful to have. Just in case the site went down or something at some point. Thanks for your work on this wonderful app!
