### ISSUE TITLE
Feature request - weather notifications on PWA

### ISSUE THREAD

**Issue by kerry-tarrant** [andrewcourtice/ocula#165]
Hi Andrew,

Do you know if it's possible to provide periodic notifications about weather updates for PWA installations of Ocula?

Currently using:
* Ocula installed using Brave (Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)) on Windows 10.
* Ocula installed on iOS with Safari.

Hope the new is off to a good start for you.

Best,
Kerry

**Comment by andrewcourtice** [comment]
Hi @kerry-tarrant 

This is something I am keen to implement but unfortunately OpenWeatherMap doesn't have realtime updates for their free services. The only way to do it currently would be to poll their API at set intervals which would rapidly breach my quota and increase the cost to run Ocula.

Hopefully I'll work something out soon as to how to do this without it being a major expense :)
