### ISSUE TITLE
Feature request - air quality index

### ISSUE THREAD

**Issue by kerry-tarrant** [andrewcourtice/ocula#166]
Would it be possible to include an air quality index within the forecast?

Notes:
* Projections for air quality are monitored and distributed to the general public on https://www.airnow.gov/. It seems limited to North America and US embassies.
* OpenWeatherMap offers air pollution through its api for free: https://openweathermap.org/api/air-pollution#concept.

**Comment by andrewcourtice** [comment]
@kerry-tarrant I'm sure I could find a way to work that in somewhere. I'll add it to the project board and hopefully get a chance to start work on it soon.
